### ISSUE TITLE
Clarify "Dried Yeast"

### ISSUE THREAD

**Issue by tdresser** [yoavweiss/recipes#2]
Is this "Instant Yeast" or "Active Dry Yeast"?

**Comment by yoavweiss** [comment]
Good point! I'm talking about [Instant yeast](https://shop.kingarthurbaking.com/items/saf-red-instant-yeast-16-oz). I'll update

**Comment by yoavweiss** [comment]
Closed by https://github.com/yoavweiss/recipes/commit/90e5ebeccdb7be8aa73d9a9e52f5375303565c42
